[package]
name = "stego"
version.workspace = true
edition.workspace = true

[dependencies]
image.workspace = true
flate2.workspace = true
crc32fast.workspace = true
anyhow.workspace = true
thiserror.workspace = true
bytes.workspace = true

[dev-dependencies]
rand = "0.8"
